spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        #注册中心地址
        server-addr: 192.168.243.128:8848
        #命名空间Id
        namespace: 0976d7fe-d265-46bb-b4dc-c73a22d89c53
        #集群名称
        cluster-name: SZ
    gateway:
      discovery:
        locator:
          #让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: consumer_route
          uri: lb://consumer
          predicates:
            #- Path=/consumer/**
            - TimeBetween=上午9:00,下午5:00
          filters:
            - name: PreLog
              args:
                name: k1
                value: v1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8000
